#!/bin/sh

init="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"

printf "Überwache Bandbreite. ENTER zum Beenden."

read -r lol

fin="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"

printf "%4sB der Bandbreite verwendet.\\n" $(numfmt --to=iec $(($fin-$init)))
