#!/usr/bin/env bash

# Quelle: Derek Taylor (http://www.gitlab.com/dwt1/)
# - Angepasst von kunde_x

# Starte Herbstluft
hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Wallpapers und Schatten
feh --no-fehbg --bg-fill --randomize /usr/share/backgrounds/kunde_x
picom &			
lxsession &

# Entferne vorhandene Keybindings
hc keyunbind --all

# Standardbefehle & Keybindings
Mod=Mod4                            		# Set super key as the main modifier
myTerm=st		               		# Set terminal
myBrowser_1=qutebrowser               		# Set browser_1
myBrowser_2=brave               		# Set browser_2
myPass=passmenu                     		# Set password manager
myMail=thunderbird                     		# Set mail manager
hc keybind $Mod-Shift-q quit	    		# Quit herbstluft session
hc keybind $Mod-Shift-r reload			# Reload herbstluft session
hc keybind $Mod-Shift-c close			# Close herbstluft window
hc keybind $Mod-Return spawn $myTerm  		# Open terminal 
hc keybind $Mod-Mod1-q spawn $myBrowser_1	# Open browser_1
hc keybind $Mod-Mod1-b spawn $myBrowser_2	# Open browser_2
hc keybind $Mod-Mod1-t spawn $myMail		# Open Mailer
hc keybind $Mod-Mod1-n spawn $myTerm -e neomutt	# Open Mailer_2
hc keybind XF86Explorer spawn $myTerm -e vifm   # Open vifm
hc keybind $Mod-e spawn $myTerm -e vifm	   	# Open vifm alternative 
hc keybind $Mod-Mod1-j spawn $myTerm -e joplin	# Open joplin
hc keybind $Mod-Mod1-r spawn $myTerm -e newsboat # Open RSS reader 
hc keybind $Mod-Mod1-m spawn $myTerm -e 'import -window root -crop 1920x1050+1920+30 screenshot.png' # Take screenshot and crop it to external screen

hc keybind $Mod-Mod1-p spawn $myPass -bw 2 -l 20 -g 6 -nb '#2f343f' -nf '#fff7bc' -sb '#83af9b' -nhf '#000000' -nhb '#ff5555' -shb '#0a81f5' -shf '#ffffff' -p 'passwörter:' -fn 'SauceCodePro Nerd Font:size=8'		# Open password manager
hc keybind $Mod-Shift-Return spawn dmenu_run -bw 2 -l 20 -g 6 -nb '#2f343f' -nf '#fff7bc' -sb '#83af9b' -nhf '#000000' -nhb '#ff5555' -shb '#0a81f5' -shf '#ffffff' -p 'menü_x:' -fn 'SauceCodePro Nerd Font:size=8'	# Open dmenu-Starter
hc keybind $Mod-Mod1-f spawn ~/.config/herbstluftwm/schriftarten.sh	             # Open Font search & display
hc keybind $Mod-Mod1-l spawn ~/.config/herbstluftwm/bookmarks.sh	             # Open bookmarks in qutebrowser
hc keybind $Mod-Shift-q spawn ~/.config/herbstluftwm/logout.sh		             # Open logout options
hc keybind $Mod-Mod1-e spawn ~/.config/herbstluftwm/file_browser.sh	             # Open dmenu file browser

# Aufpassen, dass keine Konkurrenz zu einer xbindkeys-Konfig besteht
hc keybind XF86AudioLowerVolume spawn amixer -q set Master 5%- # Alsa volume down
hc keybind XF86AudioRaiseVolume spawn amixer -q set Master 5%+ # Alsa volume up
hc keybind XF86AudioMute spawn amixer set Master toggle        # Alsa mute

# Fensterverwaltung mit VIM-Bindings
hc keybind $Mod-h                     focus left
hc keybind $Mod-j                     focus down
hc keybind $Mod-k                     focus up
hc keybind $Mod-l    		      focus right
hc keybind $Mod-Shift-h               shift left
hc keybind $Mod-Shift-j               shift down
hc keybind $Mod-Shift-k               shift up
hc keybind $Mod-Shift-l		      shift right
hc keybind $Mod-u                     split  bottom  0.5 
hc keybind $Mod-o                     split  right   0.5
hc keybind $Mod-Control-space         split explode
resizestep=0.01
hc keybind $Mod-Control-h             resize left +$resizestep
hc keybind $Mod-Control-j             resize down +$resizestep
hc keybind $Mod-Control-k             resize up +$resizestep
hc keybind $Mod-Control-l	      resize right +$resizestep

# Tags und Arbeitsbereiche
tag_names=("netz" "coding" "medien" "chat")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
# Arbeitsbereiche wechseln
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# Fensteranordnungen
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
# Maus 
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Fokusieren bei mehreren Bildschirmen 
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1

# Layout 
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set focus_follows_mouse 1

hc attr theme.active.color '#83AF9B'
hc attr theme.normal.color '#2F343F'
hc attr theme.urgent.color orange
hc attr theme.inner_width 3
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#83AF9B'
hc attr theme.active.outer_color '#83AF9B'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1

# unlock
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1920x1050+1920+30 1920x1050+0+30
# or simply:
# hc detect_monitors
hc set_monitors 1920x1050+1920+30

find the panel
  panel=~/.config/herbstluftwm/panel.sh
  [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
 for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
   # start it on each monitor
   "$panel" $monitor &
 done
