#!/usr/bin/env bash

# Source by Derek Taylor (http://www.gitlab.com/dwt1/) - Forked and customized by kunde_x

# Starte Herbstluft
hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Testbefehle

# Hintergrund und Wallpapers
xsetroot -solid '#5A8E3A'
picom &			
nitrogen --restore &
lxsession &

# remove all existing keybindings
hc keyunbind --all

# Standards
Mod=Mod4                            # Use the super key as the main modifier
myTerm=gnome-terminal               # Set my preferred terminal
myBrowser=qutebrowser               # Set my preferred browser
myPass=passmenu                     # Set my preferred password manager

#Keybindings
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $myTerm
hc keybind $Mod-e spawn $myTerm -e vim
hc keybind XF86Explorer spawn $myTerm -e vifm

# Volume bindings with Sharkoon keyboard ++Aufpassen, dass keine Konkurrenz zu einer xbindkeys-Konfig besteht++
hc keybind XF86AudioLowerVolume spawn amixer -q set Master 5%-
hc keybind XF86AudioRaiseVolume spawn amixer -q set Master 5%+
hc keybind XF86AudioMute spawn amixer set Master toggle 

# Dmenu launcher
hc keybind $Mod-Shift-Return spawn dmenu_run -bw 2 -l 20 -g 6 -nb '#2f343f' -nf '#fff7bc' -sb '#83af9b' -nhf '#000000' -nhb '#ff5555' -shb '#0a81f5' -shf '#ffffff' -p 'menü_x:' -fn 'DejaVuSansBold:pixelsize=12'

# My applications (Super+Alt+Key)
hc keybind $Mod-Mod1-q spawn $myBrowser
hc keybind $Mod-Mod1-j spawn $myTerm -e joplin
hc keybind $Mod-Mod1-p spawn $myPass -bw 2 -l 20 -g 6 -nb '#2f343f' -nf '#fff7bc' -sb '#83af9b' -nhf '#000000' -nhb '#ff5555' -shb '#0a81f5' -shf '#ffffff' -p 'passwörter:' -fn 'DejaVuSans-Bold:pixelsize=12'

# focusing clients
hc keybind $Mod-Left             focus left
hc keybind $Mod-Down             focus down
hc keybind $Mod-Up               focus up
hc keybind $Mod-Right            focus right
                              
# moving clients              
hc keybind $Mod-Shift-Left    shift left
hc keybind $Mod-Shift-Down    shift down
hc keybind $Mod-Shift-Up      shift up
hc keybind $Mod-Shift-Right   shift right

# splitting frames
hc keybind $Mod-u             split  bottom  0.5 
hc keybind $Mod-o             split  right   0.5
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Control-Left   resize left +$resizestep
hc keybind $Mod-Control-Down   resize down +$resizestep
hc keybind $Mod-Control-Up     resize up +$resizestep
hc keybind $Mod-Control-Right  resize right +$resizestep

# tags
tag_names=("netz" "coding" "medien" "chat" "system")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set focus_follows_mouse 1

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
# hc set swap_monitors_to_get_tag 1

# unlock, just to be sure
hc unlock

run polybar --reload mainbar_herbst

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
hc set_monitors 1920x1060+1920+22

find the panel
  panel=~/.config/herbstluftwm/panel.sh
  [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
 for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
   # start it on each monitor
   "$panel" $monitor &
 done
